name: gearboy # you probably want to 'snapcraft register <name>'
version: '3.7.3' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A cross-platform Game Boy & Game Boy Color emulator. # 79 char long summary
description: |
  Gearboy is a cross-platform Game Boy / Game Boy Color emulator
  written in C++ that runs on Windows, macOS, Linux, BSD, iOS,
  Raspberry Pi and RetroArch.

  _More build details: https://github.com/Joker2770/Gearboy-snap.git_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core22

plugs:
  desktop:
    mount-host-font-cache: false
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  gnome-42-2204:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-42-2204

layout:
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgweather-4:
    symlink: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgweather-4
  /usr/lib/evolution-data-server:
    symlink: $SNAP/usr/lib/evolution-data-server
  /usr/bin/gnome-control-center:
    symlink: $SNAP/usr/bin/gnome-control-center
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/share/xml/iso-codes:
    bind: $SNAP/gnome-platform/usr/share/xml/iso-codes
  /usr/share/libdrm:
    bind: $SNAP/gnome-platform/usr/share/libdrm

apps:
  gearboy:
    command: gearboy
    command-chain: ["snap/command-chain/alsa-launch"]
    environment:
      # pulseaudio
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
      SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
      GTK_USE_PORTAL: '1'
    extensions: [gnome]
    plugs:
      - home
      - alsa
      - audio-playback
      - pulseaudio
      - desktop
      - desktop-legacy
      - gsettings
      - wayland
      - unity7
      - x11
      - opengl
      - removable-media
      - mount-observe
      - joystick

parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
  gearboy:
    after: [alsa-mixin]
    plugin: make
    source: https://github.com/drhelius/Gearboy.git
    source-type: git
    source-tag: "3.6.1"
    source-subdir: platforms/linux
    # source: ../
    # artifacts: [gearboy]
    build-packages:
      - gcc
      - make
      - build-essential
      - libsdl2-dev
      - libglew-dev
      - libgtk-3-dev
    stage-packages:
      - libsdl2-2.0-0
      - libglew2.2
    override-build: |
      cd ${CRAFT_PART_BUILD}
      make -j $(nproc)
      mkdir -p ${CRAFT_PART_INSTALL}/usr/local/bin
      cp ./gearboy ${CRAFT_PART_INSTALL}/usr/local/bin/

